# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\CTA7000Programtrial.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import os
from PyQt5.QtWidgets import QApplication, QWidget, QGridLayout, QLabel, QTextEdit, QSizePolicy, QDialog
from PyQt5.QtCore import Qt, QUrl
from PyQt5 import QtCore, QtGui, QtWidgets

from tkinter import messagebox
from PyQt5.QtCore import pyqtSignal, QObject
from functools import partial
'''import Database path'''
import sqlite3
import UpdateDatabase
import SearchFile

import urllib.parse


class Ui_Main(object):
    # global Car_Num
    def __init__(self, car_num):
        self.car_num = car_num
    def setupUi(self, Main):
        Main.setObjectName("Main")
        Main.resize(1626, 1001)
        Main.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(Main)
        self.centralwidget.setStyleSheet("background-color:rgb(206, 243, 243);\n")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.ScrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.ScrollArea.setMinimumSize(QtCore.QSize(1600, 900))
        self.ScrollArea.setAutoFillBackground(True)
        self.ScrollArea.setStyleSheet("")
        self.ScrollArea.setWidgetResizable(True)
        self.ScrollArea.setObjectName("ScrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(-1629, -295, 3218, 1218))
        self.scrollAreaWidgetContents.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.MainPannel = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.MainPannel.setMinimumSize(QtCore.QSize(3200, 1200))
        self.MainPannel.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.MainPannel.setSizeIncrement(QtCore.QSize(3, 0))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.MainPannel.setFont(font)
        self.MainPannel.setStyleSheet("background-color:rgb(131, 209, 209);\n")
        # 171, 199, 227
        self.MainPannel.setObjectName("MainPannel")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.MainPannel)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 131, 1201))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.Teams = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.Teams.setContentsMargins(0, 0, 0, 0)
        self.Teams.setObjectName("Teams")
        self.team1 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.team1.setObjectName("team1")
        self.Teams.addWidget(self.team1)
        self.line = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.Teams.addWidget(self.line)
        self.team2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.team2.setObjectName("team2")
        self.Teams.addWidget(self.team2)
        self.line_2 = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.Teams.addWidget(self.line_2)
        self.team3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.team3.setObjectName("team3")
        self.Teams.addWidget(self.team3)
        self.line_3 = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.Teams.addWidget(self.line_3)
        self.team4 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.team4.setObjectName("team4")
        self.Teams.addWidget(self.team4)
        self.line_4 = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.Teams.addWidget(self.line_4)
        self.team5 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.team5.setObjectName("team5")
        self.Teams.addWidget(self.team5)
        self.line_5 = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.Teams.addWidget(self.line_5)
        self.team6 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.team6.setObjectName("team6")
        self.Teams.addWidget(self.team6)
        self.line_6 = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.Teams.addWidget(self.line_6)
        self.team7 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.team7.setObjectName("team7")
        self.Teams.addWidget(self.team7)
        self.line_7 = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.Teams.addWidget(self.line_7)
        self.team8 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.team8.setObjectName("team8")
        self.Teams.addWidget(self.team8)
        self.line_8 = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.Teams.addWidget(self.line_8)
        self.team9 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.team9.setObjectName("team9")
        self.Teams.addWidget(self.team9)
        self.line_10 = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.line_10.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.Teams.addWidget(self.line_10)
        self.team10 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.team10.setObjectName("team10")
        self.Teams.addWidget(self.team10)
        self.line_9 = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.line_9.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.Teams.addWidget(self.line_9)
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.MainPannel)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(130, 0, 3061, 111))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.Inspection = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.Inspection.setContentsMargins(0, 0, 0, 0)
        self.Inspection.setObjectName("Inspection")
        self.label1 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label1.setStyleSheet("background-color:rgb(173, 231, 231)")
        self.label1.setObjectName("label1")
        self.Inspection.addWidget(self.label1)
        self.label2 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label2.setStyleSheet("background-color:rgb(173, 231, 231)")
        self.label2.setObjectName("label2")
        self.Inspection.addWidget(self.label2)
        self.label3 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label3.setStyleSheet("background-color:rgb(173, 231, 231)")
        self.label3.setObjectName("label3")
        self.Inspection.addWidget(self.label3)
        self.label4 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label4.setStyleSheet("background-color:rgb(173, 231, 231)")
        self.label4.setObjectName("label4")
        self.Inspection.addWidget(self.label4)
        self.label5 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label5.setStyleSheet("background-color:rgb(173, 231, 231)")
        self.label5.setObjectName("label5")
        self.Inspection.addWidget(self.label5)
        self.label6 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label6.setStyleSheet("background-color:rgb(173, 231, 231)")
        self.label6.setObjectName("label6")
        self.Inspection.addWidget(self.label6)
        self.label7 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label7.setStyleSheet("background-color:rgb(173, 231, 231)")
        self.label7.setObjectName("label7")
        self.Inspection.addWidget(self.label7)
        self.label8 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label8.setStyleSheet("background-color:rgb(173, 231, 231)")
        self.label8.setObjectName("label8")
        self.Inspection.addWidget(self.label8)
        self.label9 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label9.setStyleSheet("background-color:rgb(173, 231, 231)")
        self.label9.setObjectName("label9")
        self.Inspection.addWidget(self.label9)
        self.label10 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label10.setStyleSheet("background-color:rgb(173, 231, 231)")
        self.label10.setObjectName("label10")
        self.Inspection.addWidget(self.label10)
        self.label11 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label11.setStyleSheet("background-color:rgb(173, 231, 231)")
        self.label11.setObjectName("label11")
        self.Inspection.addWidget(self.label11)
        self.label12 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label12.setStyleSheet("background-color:rgb(173, 231, 231)")
        self.label12.setObjectName("label12")
        self.Inspection.addWidget(self.label12)
        self.label_12 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_12.setStyleSheet("background-color:rgb(173, 231, 231)")
        self.label_12.setObjectName("label_12")
        self.Inspection.addWidget(self.label_12)
        self.label13 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label13.setStyleSheet("background-color:rgb(173, 231, 231)")
        self.label13.setObjectName("label13")
        self.Inspection.addWidget(self.label13)
        self.label14 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label14.setStyleSheet("background-color:rgb(173, 231, 231)")
        self.label14.setObjectName("label14")
        self.Inspection.addWidget(self.label14)
        self.label16 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label16.setStyleSheet("background-color:rgb(173, 231, 231)")
        self.label16.setObjectName("label16")
        self.Inspection.addWidget(self.label16)
        self.label17 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label17.setStyleSheet("background-color:rgb(173, 231, 231)")
        self.label17.setObjectName("label17")
        self.Inspection.addWidget(self.label17)
        self.label18 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label18.setStyleSheet("background-color:rgb(173, 231, 231)")
        self.label18.setObjectName("label18")
        self.Inspection.addWidget(self.label18)
        self.label19 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label19.setStyleSheet("background-color:rgb(173, 231, 231)")
        self.label19.setObjectName("label19")
        self.Inspection.addWidget(self.label19)
        self.label20 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label20.setStyleSheet("background-color:rgb(173, 231, 231)")
        self.label20.setObjectName("label20")
        self.Inspection.addWidget(self.label20)
        self.label21 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label21.setStyleSheet("background-color:rgb(173, 231, 231)")
        self.label21.setObjectName("label21")
        self.Inspection.addWidget(self.label21)
        self.label22 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label22.setStyleSheet("background-color:rgb(173, 231, 231)")
        self.label22.setObjectName("label22")
        self.Inspection.addWidget(self.label22)
        self.PFP = QtWidgets.QPushButton(self.MainPannel)
        self.PFP.setGeometry(QtCore.QRect(130, 170, 131, 51))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.PFP.setFont(font)
        self.PFP.setStyleSheet("QPushButton \n"
"{\n"
"    background-color:white;\n"
"    border-color:black;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: gray;\n"
"}")
        self.PFP.setObjectName("PFP")
        self.EXE = QtWidgets.QPushButton(self.MainPannel)
        self.EXE.setGeometry(QtCore.QRect(260, 750, 131, 51))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.EXE.setFont(font)
        self.EXE.setStyleSheet("QPushButton \n"
"{\n"
"    background-color:white;\n"
"    border-color:black;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: gray;\n"
"}")
        self.EXE.setObjectName("EXE")
        self.EWC = QtWidgets.QPushButton(self.MainPannel)
        self.EWC.setGeometry(QtCore.QRect(260, 860, 131, 51))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.EWC.setFont(font)
        self.EWC.setStyleSheet("QPushButton \n"
"{\n"
"    background-color:white;\n"
"    border-color:black;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: gray;\n"
"}")
        self.EWC.setObjectName("EWC")
        self.FWT = QtWidgets.QPushButton(self.MainPannel)
        self.FWT.setGeometry(QtCore.QRect(410, 170, 131, 51))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.FWT.setFont(font)
        self.FWT.setStyleSheet("QPushButton \n"
"{\n"
"    background-color:white;\n"
"    border-color:black;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: gray;\n"
"}")
        self.FWT.setObjectName("FWT")
        self.FWP = QtWidgets.QPushButton(self.MainPannel)
        self.FWP.setGeometry(QtCore.QRect(410, 120, 131, 47))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.FWP.setFont(font)
        self.FWP.setStyleSheet("QPushButton \n"
"{\n"
"    background-color:white;\n"
"    border-color:black;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: gray;\n"
"}")
        self.FWP.setObjectName("FWP")
        self.INS = QtWidgets.QPushButton(self.MainPannel)
        self.INS.setGeometry(QtCore.QRect(550, 270, 131, 51))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.INS.setFont(font)
        self.INS.setStyleSheet("QPushButton \n"
"{\n"
"    background-color:white;\n"
"    border-color:black;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: gray;\n"
"}")
        self.INS.setObjectName("INS")
        self.HE1 = QtWidgets.QPushButton(self.MainPannel)
        self.HE1.setGeometry(QtCore.QRect(690, 390, 131, 51))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.HE1.setFont(font)
        self.HE1.setStyleSheet("QPushButton \n"
"{\n"
"    background-color:white;\n"
"    border-color:black;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: gray;\n"
"}")
        self.HE1.setObjectName("HE1")
        self.CPI = QtWidgets.QPushButton(self.MainPannel)
        self.CPI.setGeometry(QtCore.QRect(550, 750, 131, 51))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.CPI.setFont(font)
        self.CPI.setStyleSheet("QPushButton \n"
"{\n"
"    background-color:white;\n"
"    border-color:black;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: gray;\n"
"}")
        self.CPI.setObjectName("CPI")
        self.UNE = QtWidgets.QPushButton(self.MainPannel)
        self.UNE.setGeometry(QtCore.QRect(690, 750, 131, 51))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.UNE.setFont(font)
        self.UNE.setStyleSheet("QPushButton \n"
"{\n"
"    background-color:white;\n"
"    border-color:black;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: gray;\n"
"}")
        self.UNE.setObjectName("UNE")
        self.FIF = QtWidgets.QPushButton(self.MainPannel)
        self.FIF.setGeometry(QtCore.QRect(690, 270, 131, 51))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.FIF.setFont(font)
        self.FIF.setStyleSheet("QPushButton \n" "{\n"
"    background-color:white;\n"
"    border-color:black;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: gray;\n"
"}")
        self.FIF.setObjectName("FIF")
        self.SBD = QtWidgets.QPushButton(self.MainPannel)
        self.SBD.setGeometry(QtCore.QRect(830, 270, 131, 51))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.SBD.setFont(font)
        self.SBD.setStyleSheet("QPushButton \n"
"{\n"
"    background-color:white;\n"
"    border-color:black;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: gray;\n"
"}")
        self.SBD.setObjectName("SBD")
        self.FIE = QtWidgets.QPushButton(self.MainPannel)
        self.FIE.setGeometry(QtCore.QRect(830, 390, 131, 51))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.FIE.setFont(font)
        self.FIE.setStyleSheet("QPushButton \n"
"{\n"
"    background-color:white;\n"
"    border-color:black;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: gray;\n"
"}")
        self.FIE.setObjectName("FIE")
        self.FCE = QtWidgets.QPushButton(self.MainPannel)
        self.FCE.setGeometry(QtCore.QRect(830, 640, 131, 51))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.FCE.setFont(font)
        self.FCE.setStyleSheet("QPushButton \n"
"{\n"
"    background-color:white;\n"
"    border-color:black;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: gray;\n"
"}")
        self.FCE.setObjectName("FCE")
        self.UWC = QtWidgets.QPushButton(self.MainPannel)
        self.UWC.setGeometry(QtCore.QRect(830, 860, 131, 51))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.UWC.setFont(font)
        self.UWC.setStyleSheet("QPushButton \n"
"{\n"
"    background-color:white;\n"
"    border-color:black;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: gray;\n"
"}")
        self.UWC.setObjectName("UWC")
        self.FIW = QtWidgets.QPushButton(self.MainPannel)
        self.FIW.setGeometry(QtCore.QRect(970, 520, 131, 51))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.FIW.setFont(font)
        self.FIW.setStyleSheet("QPushButton \n"
"{\n"
"    background-color:white;\n"
"    border-color:black;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: gray;\n"
"}")
        self.FIW.setObjectName("FIW")
        self.SIW = QtWidgets.QPushButton(self.MainPannel)
        self.SIW.setGeometry(QtCore.QRect(1110, 520, 131, 51))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.SIW.setFont(font)
        self.SIW.setStyleSheet("QPushButton \n"
"{\n"
"    background-color:white;\n"
"    border-color:black;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: gray;\n"
"}")
        self.SIW.setObjectName("SIW")
        self.SIE = QtWidgets.QPushButton(self.MainPannel)
        self.SIE.setGeometry(QtCore.QRect(970, 390, 131, 51))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.SIE.setFont(font)
        self.SIE.setStyleSheet("QPushButton \n"
"{\n"
"    background-color:white;\n"
"    border-color:black;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: gray;\n"
"}")
        self.SIE.setObjectName("SIE")
        self.SCE = QtWidgets.QPushButton(self.MainPannel)
        self.SCE.setGeometry(QtCore.QRect(1250, 640, 131, 51))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.SCE.setFont(font)
        self.SCE.setStyleSheet("QPushButton \n"
"{\n"
"    background-color:white;\n"
"    border-color:black;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: gray;\n"
"}")
        self.SCE.setObjectName("SCE")
        self.CWC = QtWidgets.QPushButton(self.MainPannel)
        self.CWC.setGeometry(QtCore.QRect(1390, 1000, 131, 51))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.CWC.setFont(font)
        self.CWC.setStyleSheet("QPushButton \n"
"{\n"
"    background-color:white;\n"
"    border-color:black;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: gray;\n"
"}")
        self.CWC.setObjectName("CWC")
        self.COT = QtWidgets.QPushButton(self.MainPannel)
        self.COT.setGeometry(QtCore.QRect(1520, 1120, 131, 51))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.COT.setFont(font)
        self.COT.setStyleSheet("QPushButton \n"
"{\n"
"    background-color:white;\n"
"    border-color:black;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: gray;\n"
"}")
        self.COT.setObjectName("COT")
        self.HPT = QtWidgets.QPushButton(self.MainPannel)
        self.HPT.setGeometry(QtCore.QRect(1670, 1120, 131, 51))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.HPT.setFont(font)
        self.HPT.setStyleSheet("QPushButton \n"
"{\n"
"    background-color:white;\n"
"    border-color:black;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: gray;\n"
"}")
        self.HPT.setObjectName("HPT")
        self.REC = QtWidgets.QPushButton(self.MainPannel)
        self.REC.setGeometry(QtCore.QRect(1800, 1000, 131, 51))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.REC.setFont(font)
        self.REC.setStyleSheet("QPushButton \n"
"{\n"
"    background-color:white;\n"
"    border-color:black;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: gray;\n"
"}")
        self.REC.setObjectName("REC")
        self.UND = QtWidgets.QPushButton(self.MainPannel)
        self.UND.setGeometry(QtCore.QRect(1940, 750, 131, 51))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.UND.setFont(font)
        self.UND.setStyleSheet("QPushButton \n"
"{\n"
"    background-color:white;\n"
"    border-color:black;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: gray;\n"
"}")
        self.UND.setObjectName("UND")
        self.ITN = QtWidgets.QPushButton(self.MainPannel)
        self.ITN.setGeometry(QtCore.QRect(2080, 390, 131, 51))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.ITN.setFont(font)
        self.ITN.setStyleSheet("QPushButton \n"
"{\n"
"    background-color:white;\n"
"    border-color:black;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: gray;\n"
"}")
        self.ITN.setObjectName("ITN")
        self.TUK = QtWidgets.QPushButton(self.MainPannel)
        self.TUK.setGeometry(QtCore.QRect(2220, 120, 131, 47))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.TUK.setFont(font)
        self.TUK.setStyleSheet("QPushButton \n"
"{\n"
"    background-color:white;\n"
"    border-color:black;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: gray;\n"
"}")
        self.TUK.setObjectName("TUK")
        self.WEG = QtWidgets.QPushButton(self.MainPannel)
        self.WEG.setGeometry(QtCore.QRect(2220, 170, 131, 51))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.WEG.setFont(font)
        self.WEG.setStyleSheet("QPushButton \n"
"{\n"
"    background-color:white;\n"
"    border-color:black;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: gray;\n"
"}")
        self.WEG.setObjectName("WEG")
        self.WCT = QtWidgets.QPushButton(self.MainPannel)
        self.WCT.setGeometry(QtCore.QRect(2222, 860, 131, 51))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.WCT.setFont(font)
        self.WCT.setStyleSheet("QPushButton \n"
"{\n"
"    background-color:white;\n"
"    border-color:black;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: gray;\n"
"}")
        self.WCT.setObjectName("WCT")
        self.GAU = QtWidgets.QPushButton(self.MainPannel)
        self.GAU.setGeometry(QtCore.QRect(2357, 111, 131, 40))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.GAU.setFont(font)
        self.GAU.setStyleSheet("QPushButton \n"
"{\n"
"    background-color:white;\n"
"    border-color:black;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: gray;\n"
"}")
        self.GAU.setObjectName("GAU")
        self.SWT = QtWidgets.QPushButton(self.MainPannel)
        self.SWT.setGeometry(QtCore.QRect(2357, 151, 131, 40))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.SWT.setFont(font)
        self.SWT.setStyleSheet("QPushButton \n"
"{\n"
"    background-color:white;\n"
"    border-color:black;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: gray;\n"
"}")
        self.SWT.setObjectName("SWT")
        self.PPR = QtWidgets.QPushButton(self.MainPannel)
        self.PPR.setGeometry(QtCore.QRect(2357, 192, 131, 42))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.PPR.setFont(font)
        self.PPR.setStyleSheet("QPushButton \n"
"{\n"
"    background-color:white;\n"
"    border-color:black;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: gray;\n"
"}")
        self.PPR.setObjectName("PPR")
        self.CUP = QtWidgets.QPushButton(self.MainPannel)
        self.CUP.setGeometry(QtCore.QRect(2500, 1120, 131, 51))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.CUP.setFont(font)
        self.CUP.setStyleSheet("QPushButton \n"
"{\n"
"    background-color:white;\n"
"    border-color:black;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: gray;\n"
"}")
        self.CUP.setObjectName("CUP")
        self.CUR = QtWidgets.QPushButton(self.MainPannel)
        self.CUR.setGeometry(QtCore.QRect(2500, 140, 131, 51))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.CUR.setFont(font)
        self.CUR.setStyleSheet("QPushButton \n"
"{\n"
"    background-color:white;\n"
"    border-color:black;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: gray;\n"
"}")
        self.CUR.setObjectName("CUR")
        self.SCS = QtWidgets.QPushButton(self.MainPannel)
        self.SCS.setGeometry(QtCore.QRect(2640, 1120, 131, 51))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.SCS.setFont(font)
        self.SCS.setStyleSheet("QPushButton \n"
"{\n"
"    background-color:white;\n"
"    border-color:black;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: gray;\n"
"}")
        self.SCS.setObjectName("SCS")
        self.DCS = QtWidgets.QPushButton(self.MainPannel)
        self.DCS.setGeometry(QtCore.QRect(2780, 1120, 131, 51))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.DCS.setFont(font)
        self.DCS.setStyleSheet("QPushButton \n"
"{\n"
"    background-color:white;\n"
"    border-color:black;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: gray;\n"
"}")
        self.DCS.setObjectName("DCS")
        self.PSI = QtWidgets.QPushButton(self.MainPannel)
        self.PSI.setGeometry(QtCore.QRect(2920, 1120, 131, 51))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.PSI.setFont(font)
        self.PSI.setStyleSheet("QPushButton \n"
"{\n"
"    background-color:white;\n"
"    border-color:black;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: gray;\n"
"}")
        self.PSI.setObjectName("PSI")
        self.DEL = QtWidgets.QPushButton(self.MainPannel)
        self.DEL.setGeometry(QtCore.QRect(3060, 1120, 131, 51))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.DEL.setFont(font)
        self.DEL.setStyleSheet("QPushButton \n"
"{\n"
"    background-color:white;\n"
"    border-color:black;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: gray;\n"
"}")
        self.DEL.setObjectName("DEL")
        self.line_11 = QtWidgets.QFrame(self.MainPannel)
        self.line_11.setGeometry(QtCore.QRect(120, 0, 16, 1201))
        self.line_11.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_11.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_11.setObjectName("line_11")
        self.testline = QtWidgets.QFrame(self.MainPannel)
        self.testline.setGeometry(QtCore.QRect(470, 295, 491, 16))
        self.testline.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.testline.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.testline.setStyleSheet("border-top: 4px solid black;")
        self.testline.setFrameShape(QtWidgets.QFrame.HLine)
        self.testline.setFrameShadow(QtWidgets.QFrame.Raised)
        self.testline.setLineWidth(0)
        self.testline.setMidLineWidth(0)
        self.testline.setObjectName("testline")
        self.testline_2 = QtWidgets.QFrame(self.MainPannel)
        self.testline_2.setGeometry(QtCore.QRect(180, 220, 16, 551))
        self.testline_2.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.testline_2.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.testline_2.setStyleSheet("border-right: 4px solid black;")
        self.testline_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.testline_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.testline_2.setLineWidth(0)
        self.testline_2.setMidLineWidth(0)
        self.testline_2.setObjectName("testline_2")
        self.testline_3 = QtWidgets.QFrame(self.MainPannel)
        self.testline_3.setGeometry(QtCore.QRect(192, 770, 181, 16))
        self.testline_3.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.testline_3.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.testline_3.setStyleSheet("border-top: 4px solid black;")
        self.testline_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.testline_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.testline_3.setLineWidth(0)
        self.testline_3.setMidLineWidth(0)
        self.testline_3.setObjectName("testline_3")
        self.testline_4 = QtWidgets.QFrame(self.MainPannel)
        self.testline_4.setGeometry(QtCore.QRect(310, 150, 20, 731))
        self.testline_4.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.testline_4.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.testline_4.setStyleSheet("border-right: 4px solid black;")
        self.testline_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.testline_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.testline_4.setLineWidth(0)
        self.testline_4.setMidLineWidth(0)
        self.testline_4.setObjectName("testline_4")
        self.testline_5 = QtWidgets.QFrame(self.MainPannel)
        self.testline_5.setGeometry(QtCore.QRect(325, 150, 161, 16))
        self.testline_5.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.testline_5.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.testline_5.setStyleSheet("border-top: 4px solid black;")
        self.testline_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.testline_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.testline_5.setLineWidth(0)
        self.testline_5.setMidLineWidth(0)
        self.testline_5.setObjectName("testline_5")
        self.testline_6 = QtWidgets.QFrame(self.MainPannel)
        self.testline_6.setGeometry(QtCore.QRect(455, 210, 20, 571))
        self.testline_6.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.testline_6.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.testline_6.setStyleSheet("border-right: 4px solid black;")
        self.testline_6.setFrameShape(QtWidgets.QFrame.VLine)
        self.testline_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.testline_6.setLineWidth(0)
        self.testline_6.setMidLineWidth(0)
        self.testline_6.setObjectName("testline_6")
        self.testline_7 = QtWidgets.QFrame(self.MainPannel)
        self.testline_7.setGeometry(QtCore.QRect(472, 775, 421, 16))
        self.testline_7.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.testline_7.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.testline_7.setStyleSheet("border-top: 4px solid black;")
        self.testline_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.testline_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.testline_7.setLineWidth(0)
        self.testline_7.setMidLineWidth(0)
        self.testline_7.setObjectName("testline_7")
        self.testline_8 = QtWidgets.QFrame(self.MainPannel)
        self.testline_8.setGeometry(QtCore.QRect(595, 290, 20, 381))
        self.testline_8.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.testline_8.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.testline_8.setStyleSheet("border-right: 4px solid black;")
        self.testline_8.setFrameShape(QtWidgets.QFrame.VLine)
        self.testline_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.testline_8.setLineWidth(0)
        self.testline_8.setMidLineWidth(0)
        self.testline_8.setObjectName("testline_8")
        self.testline_9 = QtWidgets.QFrame(self.MainPannel)
        self.testline_9.setGeometry(QtCore.QRect(1437, 666, 20, 478))
        self.testline_9.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.testline_9.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.testline_9.setStyleSheet("border-right: 4px solid black;")
        self.testline_9.setFrameShape(QtWidgets.QFrame.VLine)
        self.testline_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.testline_9.setLineWidth(0)
        self.testline_9.setMidLineWidth(0)
        self.testline_9.setObjectName("testline_9")
        self.testline_17 = QtWidgets.QFrame(self.testline_9)
        self.testline_17.setGeometry(QtCore.QRect(0, 0, 20, 478))
        self.testline_17.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.testline_17.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.testline_17.setStyleSheet("border-right: 4px solid black;")
        self.testline_17.setFrameShape(QtWidgets.QFrame.VLine)
        self.testline_17.setFrameShadow(QtWidgets.QFrame.Raised)
        self.testline_17.setLineWidth(0)
        self.testline_17.setMidLineWidth(0)
        self.testline_17.setObjectName("testline_17")
        self.testline_10 = QtWidgets.QFrame(self.MainPannel)
        self.testline_10.setGeometry(QtCore.QRect(611, 415, 561, 16))
        self.testline_10.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.testline_10.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.testline_10.setStyleSheet("border-top: 4px solid black;")
        self.testline_10.setFrameShape(QtWidgets.QFrame.HLine)
        self.testline_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.testline_10.setLineWidth(0)
        self.testline_10.setMidLineWidth(0)
        self.testline_10.setObjectName("testline_10")
        self.testline_11 = QtWidgets.QFrame(self.MainPannel)
        self.testline_11.setGeometry(QtCore.QRect(612, 665, 841, 16))
        self.testline_11.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.testline_11.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.testline_11.setStyleSheet("border-top: 4px solid black;")
        self.testline_11.setFrameShape(QtWidgets.QFrame.HLine)
        self.testline_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.testline_11.setLineWidth(0)
        self.testline_11.setMidLineWidth(0)
        self.testline_11.setObjectName("testline_11")
        self.testline_12 = QtWidgets.QFrame(self.MainPannel)
        self.testline_12.setGeometry(QtCore.QRect(740, 410, 20, 141))
        self.testline_12.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.testline_12.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.testline_12.setStyleSheet("border-right: 4px solid black;")
        self.testline_12.setFrameShape(QtWidgets.QFrame.VLine)
        self.testline_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.testline_12.setLineWidth(0)
        self.testline_12.setMidLineWidth(0)
        self.testline_12.setObjectName("testline_12")
        self.testline_13 = QtWidgets.QFrame(self.MainPannel)
        self.testline_13.setGeometry(QtCore.QRect(758, 545, 821, 16))
        self.testline_13.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.testline_13.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.testline_13.setStyleSheet("border-top: 4px solid black;")
        self.testline_13.setFrameShape(QtWidgets.QFrame.HLine)
        self.testline_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.testline_13.setLineWidth(0)
        self.testline_13.setMidLineWidth(0)
        self.testline_13.setObjectName("testline_13")
        self.testline_14 = QtWidgets.QFrame(self.MainPannel)
        self.testline_14.setGeometry(QtCore.QRect(1150, 419, 20, 135))
        self.testline_14.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.testline_14.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.testline_14.setStyleSheet("border-right: 4px solid black;")
        self.testline_14.setFrameShape(QtWidgets.QFrame.VLine)
        self.testline_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.testline_14.setLineWidth(0)
        self.testline_14.setMidLineWidth(0)
        self.testline_14.setObjectName("testline_14")
        self.testline_15 = QtWidgets.QFrame(self.MainPannel)
        self.testline_15.setGeometry(QtCore.QRect(877, 776, 20, 371))
        self.testline_15.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.testline_15.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.testline_15.setStyleSheet("border-right: 4px solid black;")
        self.testline_15.setFrameShape(QtWidgets.QFrame.VLine)
        self.testline_15.setFrameShadow(QtWidgets.QFrame.Raised)
        self.testline_15.setLineWidth(0)
        self.testline_15.setMidLineWidth(0)
        self.testline_15.setObjectName("testline_15")
        self.testline_16 = QtWidgets.QFrame(self.MainPannel)
        self.testline_16.setGeometry(QtCore.QRect(893, 1143, 971, 16))
        self.testline_16.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.testline_16.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.testline_16.setStyleSheet("border-top: 4px solid black;")
        self.testline_16.setFrameShape(QtWidgets.QFrame.HLine)
        self.testline_16.setFrameShadow(QtWidgets.QFrame.Raised)
        self.testline_16.setLineWidth(0)
        self.testline_16.setMidLineWidth(0)
        self.testline_16.setObjectName("testline_16")
        self.testline_18 = QtWidgets.QFrame(self.MainPannel)
        self.testline_18.setGeometry(QtCore.QRect(1563, 546, 20, 601))
        self.testline_18.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.testline_18.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.testline_18.setStyleSheet("border-right: 4px solid black;")
        self.testline_18.setFrameShape(QtWidgets.QFrame.VLine)
        self.testline_18.setFrameShadow(QtWidgets.QFrame.Raised)
        self.testline_18.setLineWidth(0)
        self.testline_18.setMidLineWidth(0)
        self.testline_18.setObjectName("testline_18")
        self.testline_19 = QtWidgets.QFrame(self.MainPannel)
        self.testline_19.setGeometry(QtCore.QRect(1846, 414, 20, 731))
        self.testline_19.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.testline_19.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.testline_19.setStyleSheet("border-right: 4px solid black;")
        self.testline_19.setFrameShape(QtWidgets.QFrame.VLine)
        self.testline_19.setFrameShadow(QtWidgets.QFrame.Raised)
        self.testline_19.setLineWidth(0)
        self.testline_19.setMidLineWidth(0)
        self.testline_19.setObjectName("testline_19")
        self.testline_20 = QtWidgets.QFrame(self.MainPannel)
        self.testline_20.setGeometry(QtCore.QRect(1860, 770, 291, 16))
        self.testline_20.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.testline_20.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.testline_20.setStyleSheet("border-top: 4px solid black;")
        self.testline_20.setFrameShape(QtWidgets.QFrame.HLine)
        self.testline_20.setFrameShadow(QtWidgets.QFrame.Raised)
        self.testline_20.setLineWidth(0)
        self.testline_20.setMidLineWidth(0)
        self.testline_20.setObjectName("testline_20")
        self.testline_21 = QtWidgets.QFrame(self.MainPannel)
        self.testline_21.setGeometry(QtCore.QRect(1865, 413, 281, 16))
        self.testline_21.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.testline_21.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.testline_21.setStyleSheet("border-top: 4px solid black;")
        self.testline_21.setFrameShape(QtWidgets.QFrame.HLine)
        self.testline_21.setFrameShadow(QtWidgets.QFrame.Raised)
        self.testline_21.setLineWidth(0)
        self.testline_21.setMidLineWidth(0)
        self.testline_21.setObjectName("testline_21")
        self.testline_22 = QtWidgets.QFrame(self.MainPannel)
        self.testline_22.setGeometry(QtCore.QRect(2130, 143, 20, 631))
        self.testline_22.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.testline_22.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.testline_22.setStyleSheet("border-right: 4px solid black;")
        self.testline_22.setFrameShape(QtWidgets.QFrame.VLine)
        self.testline_22.setFrameShadow(QtWidgets.QFrame.Raised)
        self.testline_22.setLineWidth(0)
        self.testline_22.setMidLineWidth(0)
        self.testline_22.setObjectName("testline_22")
        self.testline_23 = QtWidgets.QFrame(self.MainPannel)
        self.testline_23.setGeometry(QtCore.QRect(2150, 143, 131, 16))
        self.testline_23.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.testline_23.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.testline_23.setStyleSheet("border-top: 4px solid black;")
        self.testline_23.setFrameShape(QtWidgets.QFrame.HLine)
        self.testline_23.setFrameShadow(QtWidgets.QFrame.Raised)
        self.testline_23.setLineWidth(0)
        self.testline_23.setMidLineWidth(0)
        self.testline_23.setObjectName("testline_23")
        self.testline_24 = QtWidgets.QFrame(self.MainPannel)
        self.testline_24.setGeometry(QtCore.QRect(2270, 140, 20, 741))
        self.testline_24.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.testline_24.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.testline_24.setStyleSheet("border-right: 4px solid black;")
        self.testline_24.setFrameShape(QtWidgets.QFrame.VLine)
        self.testline_24.setFrameShadow(QtWidgets.QFrame.Raised)
        self.testline_24.setLineWidth(0)
        self.testline_24.setMidLineWidth(0)
        self.testline_24.setObjectName("testline_24")
        self.testline_25 = QtWidgets.QFrame(self.MainPannel)
        self.testline_25.setGeometry(QtCore.QRect(2440, 220, 20, 931))
        self.testline_25.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.testline_25.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.testline_25.setStyleSheet("border-right: 4px solid black;")
        self.testline_25.setFrameShape(QtWidgets.QFrame.VLine)
        self.testline_25.setFrameShadow(QtWidgets.QFrame.Raised)
        self.testline_25.setLineWidth(0)
        self.testline_25.setMidLineWidth(0)
        self.testline_25.setObjectName("testline_25")
        self.testline_26 = QtWidgets.QFrame(self.MainPannel)
        self.testline_26.setGeometry(QtCore.QRect(2370, 220, 20, 671))
        self.testline_26.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.testline_26.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.testline_26.setStyleSheet("border-right: 4px solid black;")
        self.testline_26.setFrameShape(QtWidgets.QFrame.VLine)
        self.testline_26.setFrameShadow(QtWidgets.QFrame.Raised)
        self.testline_26.setLineWidth(0)
        self.testline_26.setMidLineWidth(0)
        self.testline_26.setObjectName("testline_26")
        self.testline_27 = QtWidgets.QFrame(self.MainPannel)
        self.testline_27.setGeometry(QtCore.QRect(2290, 890, 101, 16))
        self.testline_27.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.testline_27.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.testline_27.setStyleSheet("border-top: 4px solid black;")
        self.testline_27.setFrameShape(QtWidgets.QFrame.HLine)
        self.testline_27.setFrameShadow(QtWidgets.QFrame.Raised)
        self.testline_27.setLineWidth(0)
        self.testline_27.setMidLineWidth(0)
        self.testline_27.setObjectName("testline_27")
        self.testline_28 = QtWidgets.QFrame(self.MainPannel)
        self.testline_28.setGeometry(QtCore.QRect(2457, 1148, 101, 16))
        self.testline_28.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.testline_28.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.testline_28.setStyleSheet("border-top: 4px solid black;")
        self.testline_28.setFrameShape(QtWidgets.QFrame.HLine)
        self.testline_28.setFrameShadow(QtWidgets.QFrame.Raised)
        self.testline_28.setLineWidth(0)
        self.testline_28.setMidLineWidth(0)
        self.testline_28.setObjectName("testline_28")
        self.testline_29 = QtWidgets.QFrame(self.MainPannel)
        self.testline_29.setGeometry(QtCore.QRect(2550, 170, 20, 981))
        self.testline_29.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.testline_29.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.testline_29.setStyleSheet("border-right: 4px solid black;")
        self.testline_29.setFrameShape(QtWidgets.QFrame.VLine)
        self.testline_29.setFrameShadow(QtWidgets.QFrame.Raised)
        self.testline_29.setLineWidth(0)
        self.testline_29.setMidLineWidth(0)
        self.testline_29.setObjectName("testline_29")
        self.testline_30 = QtWidgets.QFrame(self.MainPannel)
        self.testline_30.setGeometry(QtCore.QRect(2570, 166, 141, 16))
        self.testline_30.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.testline_30.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.testline_30.setStyleSheet("border-top: 4px solid black;")
        self.testline_30.setFrameShape(QtWidgets.QFrame.HLine)
        self.testline_30.setFrameShadow(QtWidgets.QFrame.Raised)
        self.testline_30.setLineWidth(0)
        self.testline_30.setMidLineWidth(0)
        self.testline_30.setObjectName("testline_30")
        self.testline_31 = QtWidgets.QFrame(self.MainPannel)
        self.testline_31.setGeometry(QtCore.QRect(2690, 170, 20, 981))
        self.testline_31.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.testline_31.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.testline_31.setStyleSheet("border-right: 4px solid black;")
        self.testline_31.setFrameShape(QtWidgets.QFrame.VLine)
        self.testline_31.setFrameShadow(QtWidgets.QFrame.Raised)
        self.testline_31.setLineWidth(0)
        self.testline_31.setMidLineWidth(0)
        self.testline_31.setObjectName("testline_31")
        self.testline_32 = QtWidgets.QFrame(self.MainPannel)
        self.testline_32.setGeometry(QtCore.QRect(2710, 1140, 411, 16))
        self.testline_32.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.testline_32.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.testline_32.setStyleSheet("border-top: 4px solid black;")
        self.testline_32.setFrameShape(QtWidgets.QFrame.HLine)
        self.testline_32.setFrameShadow(QtWidgets.QFrame.Raised)
        self.testline_32.setLineWidth(0)
        self.testline_32.setMidLineWidth(0)
        self.testline_32.setObjectName("testline_32")
        self.INI = QtWidgets.QPushButton(self.MainPannel)
        self.INI.setGeometry(QtCore.QRect(135, 120, 126, 51))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.INI.setFont(font)
        self.INI.setStyleSheet("QPushButton \n"
"{\n"
"    background-color:white;\n"
"    border-color:black;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: gray;\n"
"}")
        self.INI.setObjectName("INI")
        self.label = QtWidgets.QLabel(self.MainPannel)
        self.label.setGeometry(QtCore.QRect(227, 120, 31, 31))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(".\\Untitled.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.MainPannel)
        self.label_2.setGeometry(QtCore.QRect(508, 170, 31, 31))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap(".\\Untitled.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.MainPannel)
        self.label_3.setGeometry(QtCore.QRect(1068, 520, 31, 31))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap(".\\Untitled.png"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.MainPannel)
        self.label_4.setGeometry(QtCore.QRect(788, 750, 31, 31))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap(".\\Untitled.png"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.MainPannel)
        self.label_5.setGeometry(QtCore.QRect(1905, 1000, 25, 25))
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap(".\\Untitled.png"))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.MainPannel)
        self.label_6.setGeometry(QtCore.QRect(2038, 750, 31, 31))
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap(".\\Untitled.png"))
        self.label_6.setScaledContents(True)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.MainPannel)
        self.label_7.setGeometry(QtCore.QRect(2453, 151, 31, 31))
        self.label_7.setText("")
        self.label_7.setPixmap(QtGui.QPixmap(".\\Untitled.png"))
        self.label_7.setScaledContents(True)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.MainPannel)
        self.label_8.setGeometry(QtCore.QRect(3018, 1120, 31, 31))
        self.label_8.setText("")
        self.label_8.setPixmap(QtGui.QPixmap(".\\Untitled.png"))
        self.label_8.setScaledContents(True)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.MainPannel)
        self.label_9.setGeometry(QtCore.QRect(3158, 1119, 31, 31))
        self.label_9.setText("")
        self.label_9.setPixmap(QtGui.QPixmap(".\\Untitled.png"))
        self.label_9.setScaledContents(True)
        self.label_9.setObjectName("label_9")
        self.testline_32.raise_()
        self.testline_30.raise_()
        self.testline_31.raise_()
        self.testline_29.raise_()
        self.testline_28.raise_()
        self.testline_25.raise_()
        self.testline_26.raise_()
        self.testline_27.raise_()
        self.testline_23.raise_()
        self.testline_24.raise_()
        self.testline_21.raise_()
        self.testline_22.raise_()
        self.testline_20.raise_()
        self.testline_19.raise_()
        self.testline_18.raise_()
        self.testline_13.raise_()
        self.testline_9.raise_()
        self.testline_16.raise_()
        self.testline_15.raise_()
        self.testline_10.raise_()
        self.testline_14.raise_()
        self.testline_12.raise_()
        self.testline_11.raise_()
        self.testline_8.raise_()
        self.testline_7.raise_()
        self.testline.raise_()
        self.testline_6.raise_()
        self.testline_5.raise_()
        self.testline_4.raise_()
        self.testline_3.raise_()
        self.testline_2.raise_()
        self.verticalLayoutWidget.raise_()
        self.horizontalLayoutWidget.raise_()
        self.PFP.raise_()
        self.EXE.raise_()
        self.EWC.raise_()
        self.FWT.raise_()
        self.FWP.raise_()
        self.INS.raise_()
        self.HE1.raise_()
        self.CPI.raise_()
        self.UNE.raise_()
        self.FIF.raise_()
        self.SBD.raise_()
        self.FIE.raise_()
        self.FCE.raise_()
        self.UWC.raise_()
        self.FIW.raise_()
        self.SIW.raise_()
        self.SIE.raise_()
        self.SCE.raise_()
        self.CWC.raise_()
        self.COT.raise_()
        self.HPT.raise_()
        self.REC.raise_()
        self.UND.raise_()
        self.ITN.raise_()
        self.TUK.raise_()
        self.WEG.raise_()
        self.WCT.raise_()
        self.GAU.raise_()
        self.SWT.raise_()
        self.PPR.raise_()
        self.CUP.raise_()
        self.CUR.raise_()
        self.SCS.raise_()
        self.DCS.raise_()
        self.PSI.raise_()
        self.DEL.raise_()
        self.line_11.raise_()
        self.INI.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.label_4.raise_()
        self.label_5.raise_()
        self.label_6.raise_()
        self.label_7.raise_()
        self.label_8.raise_()
        self.label_9.raise_()
        self.verticalLayout_2.addWidget(self.MainPannel)
        self.ScrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.ScrollArea)
        Main.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Main)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1626, 21))
        self.menubar.setObjectName("menubar")
        Main.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Main)
        self.statusbar.setObjectName("statusbar")
        Main.setStatusBar(self.statusbar)

        self.retranslateUi(Main)
        QtCore.QMetaObject.connectSlotsByName(Main)

    def retranslateUi(self, Main):
        _translate = QtCore.QCoreApplication.translate
        Main.setWindowTitle(_translate("Main", f"{self.car_num} Inspection Diagram"))
        self.team1.setText(_translate("Main", "<html><head/><body><p align=\"center\"><span style=\" font-size:11pt; font-weight:600;\">班组</span></p><p align=\"center\"><span style=\" font-size:11pt;\">Work Team</span></p></body></html>"))
        self.team2.setText(_translate("Main", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; font-weight:600;\">落车</span></p><p align=\"center\"><span style=\" font-size:10pt; font-weight:600;\">Truking</span></p></body></html>"))
        self.team3.setText(_translate("Main", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; font-weight:600;\">内装</span></p><p align=\"center\"><span style=\" font-size:10pt; font-weight:600;\">Interior </span></p><p align=\"center\"><span style=\" font-size:10pt; font-weight:600;\">Furnishing</span></p></body></html>"))
        self.team4.setText(_translate("Main", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; font-weight:600;\">内设</span></p><p align=\"center\"><span style=\" font-size:10pt; font-weight:600;\">Interior</span></p><p align=\"center\"><span style=\" font-size:10pt; font-weight:600;\">Equipment</span></p></body></html>"))
        self.team5.setText(_translate("Main", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; font-weight:600;\">内设电气</span></p><p align=\"center\"><span style=\" font-size:10pt; font-weight:600;\">Interior </span></p><p align=\"center\"><span style=\" font-size:10pt; font-weight:600;\">Electrical</span></p></body></html>"))
        self.team6.setText(_translate("Main", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; font-weight:600;\">司机室</span></p><p align=\"center\"><span style=\" font-size:10pt; font-weight:600;\">Cab</span></p></body></html>"))
        self.team7.setText(_translate("Main", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; font-weight:600;\">车外设备</span></p><p align=\"center\"><span style=\" font-size:10pt; font-weight:600;\">Exterior </span></p><p align=\"center\"><span style=\" font-size:10pt; font-weight:600;\">Equipment</span></p></body></html>"))
        self.team8.setText(_translate("Main", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; font-weight:600;\">车外电气</span></p><p align=\"center\"><span style=\" font-size:10pt; font-weight:600;\">Exterior </span></p><p align=\"center\"><span style=\" font-size:10pt; font-weight:600;\">Electrical</span></p></body></html>"))
        self.team9.setText(_translate("Main", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; font-weight:600;\">司机室电气</span></p><p align=\"center\"><span style=\" font-size:10pt; font-weight:600;\">Cab</span></p><p align=\"center\"><span style=\" font-size:10pt; font-weight:600;\">Electrical</span></p></body></html>"))
        self.team10.setText(_translate("Main", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; font-weight:600;\">调试</span></p><p align=\"center\"><span style=\" font-size:10pt; font-weight:600;\">Commissioning</span></p></body></html>"))
        self.label1.setText(_translate("Main", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; font-weight:600;\">检车检查</span></p><p align=\"center\"><span style=\" font-size:10pt; font-weight:600;\">Incoming</span></p><p align=\"center\"><span style=\" font-size:10pt; font-weight:600;\">Inspection</span></p></body></html>"))
        self.label2.setText(_translate("Main", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; font-weight:600;\">外设</span></p><p align=\"center\"><span style=\" font-size:10pt; font-weight:600;\">Exterior</span></p><p align=\"center\"><span style=\" font-size:10pt; font-weight:600;\">Equipment</span></p></body></html>"))
        self.label3.setText(_translate("Main", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; font-weight:600;\">一次淋雨</span></p><p align=\"center\"><span style=\" font-size:10pt; font-weight:600;\">1st </span></p><p align=\"center\"><span style=\" font-size:10pt; font-weight:600;\">Water Test</span></p></body></html>"))
        self.label4.setText(_translate("Main", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; font-weight:600;\">防寒</span></p><p align=\"center\"><span style=\" font-size:10pt; font-weight:600;\">Insulation</span></p></body></html>"))
        self.label5.setText(_translate("Main", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.label6.setText(_translate("Main", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.label7.setText(_translate("Main", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.label8.setText(_translate("Main", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.label9.setText(_translate("Main", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.label10.setText(_translate("Main", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.label11.setText(_translate("Main", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; font-weight:600;\">校线</span></p><p align=\"center\"><span style=\" font-size:10pt; font-weight:600;\">Continuity</span></p><p align=\"center\"><span style=\" font-size:10pt; font-weight:600;\">Test</span></p></body></html>"))
        self.label12.setText(_translate("Main", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; font-weight:600;\">耐压</span></p><p align=\"center\"><span style=\" font-size:10pt; font-weight:600;\">Hi-Post</span></p><p align=\"center\"><span style=\" font-size:10pt; font-weight:600;\">Test</span></p></body></html>"))
        self.label_12.setText(_translate("Main", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; font-weight:600;\">耐压后恢复</span></p><p align=\"center\"><span style=\" font-size:10pt; font-weight:600;\">Recvoery</span></p><p align=\"center\"><span style=\" font-size:10pt; font-weight:600;\">Test</span></p></body></html>"))
        self.label13.setText(_translate("Main", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; font-weight:600;\">车外细检</span></p><p align=\"center\"><span style=\" font-size:10pt; font-weight:600;\">Ext Detail</span></p><p align=\"center\"><span style=\" font-size:10pt; font-weight:600;\">Inspection</span></p></body></html>"))
        self.label14.setText(_translate("Main", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; font-weight:600;\">车内细检</span></p><p align=\"center\"><span style=\" font-size:10pt; font-weight:600;\">Int Detail</span></p><p align=\"center\"><span style=\" font-size:10pt; font-weight:600;\">Inspection</span></p></body></html>"))
        self.label16.setText(_translate("Main", "<html><head/><body><p align=\"center\"><span style=\" font-size:11pt; font-weight:600;\">落车</span></p><p align=\"center\"><span style=\" font-size:11pt; font-weight:600;\">Trucking</span></p></body></html>"))
        self.label17.setText(_translate("Main", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; font-weight:600;\">二次淋雨</span></p><p align=\"center\"><span style=\" font-size:10pt; font-weight:600;\">2nd Waster</span></p><p align=\"center\"><span style=\" font-size:10pt; font-weight:600;\">Test</span></p></body></html>"))
        self.label18.setText(_translate("Main", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; font-weight:600;\">编组</span></p><p align=\"center\"><span style=\" font-size:10pt; font-weight:600;\">Coupling</span></p></body></html>"))
        self.label19.setText(_translate("Main", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; font-weight:600;\">静调</span></p><p align=\"center\"><span style=\" font-size:10pt; font-weight:600;\">Static</span></p><p align=\"center\"><span style=\" font-size:10pt; font-weight:600;\">Test</span></p></body></html>"))
        self.label20.setText(_translate("Main", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; font-weight:600;\">动调</span></p><p align=\"center\"><span style=\" font-size:10pt; font-weight:600;\">Dynamic</span></p><p align=\"center\"><span style=\" font-size:10pt; font-weight:600;\">Test</span></p></body></html>"))
        self.label21.setText(_translate("Main", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; font-weight:600;\">最终交检</span></p><p align=\"center\"><span style=\" font-size:10pt; font-weight:600;\">Final Inspection </span></p><p align=\"center\"><span style=\" font-size:10pt; font-weight:600;\">PSI</span></p></body></html>"))
        self.label22.setText(_translate("Main", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; font-weight:600;\">发运前检查</span></p><p align=\"center\"><span style=\" font-size:10pt; font-weight:600;\">Before Delivery</span></p></body></html>"))


        self.PFP.setText(_translate("Main", "管道清理保压\nPFP\nPipe Pressure Test"))
        self.EXE.setText(_translate("Main", "外部设备\n"
                "EXE\n"
                "Exterior Equipment"))
        self.EWC.setText(_translate("Main", "车外接线\n"
                "EWC\n"
                "Exterior Wire Connection"))
        self.FWT.setText(_translate("Main", "一次淋雨\n"
                "1WT\n"
                "1st Water Test"))
        self.FWP.setText(_translate("Main", "一次淋雨防护\n"
                "1WP\n"
                "1st Water Test Protection"))
        self.INS.setText(_translate("Main", "防寒\n"
                "INS\n"
                "Insulation"))
        self.HE1.setText(_translate("Main", "电加热1\n"
                "HE1\n"
                "Heater 1"))
        self.CPI.setText(_translate("Main", "车钩安装\n"
                "CPI\n"
                "Coupler Installation"))
        self.UNE.setText(_translate("Main", "车下设备\n"
                "UNE\n"
                "Underframe Wire Conn"))
        self.FIF.setText(_translate("Main", "内装一次交检\n"
                "1IF\n"
                "1st Interior Furnishing"))
        self.SBD.setText(_translate("Main", "角踢板\n"
                "SBD\n"
                "Skirt Board"))
        self.FIE.setText(_translate("Main", "车内设备\n"
                "1IE\n"
                "1st Interior Equipment"))
        self.FCE.setText(_translate("Main", "一次司机室设备\n"
                "1CE\n"
                "1st Cab Equipment"))
        self.UWC.setText(_translate("Main", "车下接线\n"
                "UWC\n"
                "Underframe Wire Conn"))
        self.FIW.setText(_translate("Main", "客室一次接线\n"
                "1IW\n"
                "1st Interior Wire Conn"))
        self.SIW.setText(_translate("Main", "客室二次接线\n"
                "2IW\n"
                "2nd Interior Wire Conn"))
        self.SIE.setText(_translate("Main", "车内设备二次交检\n"
                "2IE\n"
                "2nd Interior Equipment"))
        self.SCE.setText(_translate("Main", "二次司机室设备\n"
                "2CE\n"
                "2nd Cab Equipment"))
        self.CWC.setText(_translate("Main", "司机室接线\n"
                "CWC\n"
                "Cab Wire Conn"))
        self.COT.setText(_translate("Main", "校线\n"
                "COT\n"
                "Continuity Test"))
        self.HPT.setText(_translate("Main", "绝缘耐压\n"
                "HPT\n"
                "Hipot Test"))
        self.REC.setText(_translate("Main", "耐压后接线恢复\n"
                "REC\n"
                "Wire Recovery After Hipot"))
        self.UND.setText(_translate("Main", "车下细检\n"
                "UND\n"
                "Underframe Inspection"))
        self.ITN.setText(_translate("Main", "车内细检\n"
                "ITN\n"
                "Interior Inspection"))
        self.TUK.setText(_translate("Main", "落车\n"
                "TUK\n"
                "Trucking"))
        self.WEG.setText(_translate("Main", "称重\n"
                "WEG\n"
                "Weighting"))
        self.WCT.setText(_translate("Main", "落车后转向架接线\n"
                "WCT\n"
                "Wire Conn w Bogie"))
        self.GAU.setText(_translate("Main", "界限\n"
                "GAU\n"
                "Gauge Test"))
        self.SWT.setText(_translate("Main", "2次淋雨\n"
                "2WT\n"
                "2nd water Test"))
        self.PPR.setText(_translate("Main", "管路注油排气\n"
                "PPR\n"
                "Pipe Refill"))
        self.CUP.setText(_translate("Main", "编组\n"
                "CUP\n"
                "Coupling"))
        self.CUR.setText(_translate("Main", "曲线试验\n"
                "CUR\n"
                "Curve Test"))
        self.SCS.setText(_translate("Main", "静态调试\n"
                "SCS\n"
                "Static Commissioning"))
        self.DCS.setText(_translate("Main", "动态调试\n"
                "DCS\n"
                "Dynamic Commissioning"))
        self.PSI.setText(_translate("Main", "发运前检查\n"
                "PSI\n"
                "PSI"))
        self.DEL.setText(_translate("Main", "包装发运\n"
                "DEL\n"
                "Delivery"))
        self.INI.setText(_translate("Main", "接车检查\n"
                "INI\n"
                "Incomn. Inspection"))

        #combine button list
        self.cist = [self.INI, self.PFP, self.EXE, self.EWC, self.FWP, self.FWT, self.INS, self.FIF, self.SBD, self.HE1,
                     self.FIE, self.SIE, self.FIW, self.SIW, self.FCE, self.SCE, self.CPI, self.UNE, self.UWC, self.CWC,
                     self.COT, self.HPT, self.REC, self.UND, self.ITN, self.TUK, self.WEG, self.WCT, self.GAU, self.SWT,
                     self.PPR, self.CUP, self.CUR, self.SCS, self.DCS, self.PSI, self.DEL]


#Red/Pink Label "background-color: #ffcccb;"

# def main(carnum, inspStatus):
class InspOverview():
    #
    # def __init__(self):
    #     self.signal = InspOverviewSignal()
    #     self.signal.insp_overview_requested.connect(self.main)

    def main(self, app, carNum, Insp):

        # The rest of the method remains unchanged
        insp = carNum.upper() + Insp.upper()

        exr, er, rrn = [], [], []
        exrS, erS = [], []
        ppi = ""
        print("Database path:", UpdateDatabase.path)

        con = sqlite3.connect(UpdateDatabase.path)
        cur = con.cursor()
        '''get current rrn, exr, er, ppi status'''


        print("current insp is ", insp)
        cur.execute(f"""Select * from CarInsp""")
        ls = cur.fetchall()
        for i in ls:
            print(i)
        cur.execute(f"""Select RRN, EXR, ER, PPI from CarInsp where Car_INSP_Point = '{insp}'""")
        inspDetail = cur.fetchone()
        print(inspDetail)
        if inspDetail:
                # '''rrn portion'''
            if inspDetail[0]:
                try:
                    rrn = inspDetail[0].split(",")
                except AttributeError:
                    rrn = rrn.append(inspDetail[0])
                    print("Only one rrn available")
                else:
                    print("rrn successfully extracted")

                #exr portion
            if inspDetail[1]:
                try:
                    exr = inspDetail[1].split(",")
                    print(exr)
                except AttributeError:
                    exr = rrn.append(inspDetail[1])
                    print("Only one exr available")
                else:
                    print("exr successfully extracted")

                for i in exr:
                    cur.execute(f"""Select EXR_Status from EXR where EXR_Num = '{i}'""")
                    status = cur.fetchone()
                    exrS.append(status[0])

                #er portion
            if inspDetail[2]:
                print(inspDetail[2])
                try:
                    er = inspDetail[2].split(",")
                    print("check12")
                except AttributeError:
                    er.append(inspDetail[2])
                    print("Only one er available")
                else:
                    print("er successfully extracted")

                for i in er:
                    cur.execute(f"""Select ER_Status from ER where ER_Num = '{i}'""")
                    status = cur.fetchone()
                    erS.append(status[0])
            if inspDetail[3]:
                ppi = inspDetail[3]
            else:
                ppi = None

            #jump to memory block 3

            # print(er)
            # print(erS)
            # print(exr)
            # print(exrS)
            con.close()
        else:
            messagebox.showerror(message=f"Car_INSP_Point is not allocated yet.")
            con.close()
            return False

        # app = QApplication([])
        # window = QWidget()
        window = QDialog()
        window.setWindowTitle(f"{carNum} {Insp} Overview")

        # Create a QGridLayout with two columns
        layout = QGridLayout(window)
        layout.setColumnStretch(1, 1)

        # Create labels and text for the first column
        rrn_label = QLabel("RRN:", window)
        exr_label = QLabel("EXR Stop Point:", window)
        er_label = QLabel("ER Stop Point:", window)
        ppi_label = QLabel("PPI:", window)
        rrn_text = QLabel("", window)

        #get the recent path location of those rrns
        for x in rrn:
            current = rrn_text.text()
            try:
                path = SearchFile.Search.searchRRN(x, carNum, Insp)
                # print(f"current path {path}")
                rrn_text.setText(current + f"<a href='file:///{path}'>{x}</a>\t")

            except Exception as e:
                rrn_text.setText(current + f"{x}\t")

        rrn_text.setOpenExternalLinks(True)
        rrn_text.setTextFormat(Qt.RichText)


        '''exr text if closed, then strike out'''
        exr_text = QLabel(window)
        exr_text.setText("")

        for y, z in zip(exr, exrS):
            current = exr_text.text()
            try:
                path = SearchFile.Search.searchEXR(y, carNum, Insp)
                if z.upper() == "CLOSED":
                    print(path)
                    # exr_text.setText(current + f"<a href='file:///{path}'><strike>{y}</strike></a>\t")
                    exr_text.setText(current + f"<a href='file:///{path}'><s>{y}</s></a>\t")

                elif z.upper == "OPEN":
                    exr_text.setText(current + f"<a href='file:///{path}'>{y}</a>\t")

            except Exception as e:
                if z is None:
                    messagebox.showinfo(message=f"no information about {z} in EXR Database")
                    return False
                elif z.upper() == "CLOSED":
                    exr_text.setText(current + f"<strike>{y}</strike>\t")
                elif z.upper == "OPEN":
                    exr_text.setText(current + f"{y}\t")


        exr_text.setTextFormat(Qt.RichText)
        exr_text.setOpenExternalLinks(True)

        # Create a label for the ER Stop Point with a hyperlink for "56.78"
        er_text = QLabel(window)
        er_text.setText("")
        for y, z in zip(er, erS):
            current = er_text.text()
            try:
                path = SearchFile.Search.searchER(y, carNum, Insp)
                if z.upper() == "CLOSED":
                    er_text.setText(current + f"<a href='file:///{path}'><strike>{y}</strike></a>\t")
                elif z.upper == "OPEN":
                    er_text.setText(current + f"<a href='file:///{path}'>{y}</a>\t")

            except Exception as e:
                if z is None:
                    messagebox.showinfo(message=f"no information about {z} in ER Database")
                    return False
                elif z.upper() == "CLOSED":
                    er_text.setText(current + f"<strike>{y}</strike>\t")
                elif z.upper == "OPEN":
                    er_text.setText(current + f"{y}\t")
        er_text.setTextFormat(Qt.RichText)
        er_text.setOpenExternalLinks(True)



        ppi_text = QLabel(window)
        if ppi is None:
            ppi_text.setText("")
        else:
            path = SearchFile.Search.searchPPI(carNum, Insp)
            if path:
                ppi_text.setText(f"<a href='file:///{path}'>{ppi}</a>")
            else:
                ppi_text.setText(f"{ppi}")
        ppi_text.setOpenExternalLinks(True)
        # Set the size policy of the text widgets to Expanding

        rrn_text.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
        exr_text.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
        er_text.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
        ppi_text.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)

        # Add the labels and text to the layout
        layout.addWidget(rrn_label, 0, 0)
        layout.addWidget(exr_label, 1, 0)
        layout.addWidget(er_label, 2, 0)
        layout.addWidget(ppi_label, 3, 0)

        layout.addWidget(rrn_text, 0, 1)
        layout.addWidget(exr_text, 1, 1)
        layout.addWidget(er_text, 2, 1)
        layout.addWidget(ppi_text, 3, 1)

        # Set the window size
        window.resize(500, 300)

        window.show()
        # app.exec_()
        window.exec_()

def main(carnum, SList):
    import sys
    '''grab the function by values'''

    app = QtWidgets.QApplication(sys.argv)
    Main = QtWidgets.QMainWindow()
    ui = Ui_Main(car_num=carnum)
    ui.setupUi(Main)


    '''car number shows the location of the inspection point'''
    itemNum = 0
    IList = ["INI", "PFP", "EXE", "EWC", "1WP", "1WT", "INS", "1IF", "SBD", "HE1",
             "1IE", "2IE", "1IW", "2IW", "1CE", "2CE", "CPI", "UNE", "UWC", "CWC",
             "COT", "HPT", "REC", "UND", "ITN", "TUK", "WEG", "WCT", "GAU", "2WT",
             "PPR", "CUP", "CUR", "SCS", "DCS", "PSI", "DEL"]

    insp_overview = InspOverview()
    ui.cist[0].clicked.connect(lambda: insp_overview.main(app, ui.car_num, "2IW"))
    ui.cist[1].clicked.connect(lambda: insp_overview.main(app, ui.car_num, "2IW"))


    # for button, insp in zip(ui.cist, IList):
    #     button.clicked.connect(partial(insp_overview.signal.insp_overview_requested.emit, app, ui.car_num, insp))



    for i in SList:
        if i.upper() == "COMPLETED":
            ui.cist[itemNum].setStyleSheet("background-color: #90ee90;")
        elif i.upper() == "PENDING":
            ui.cist[itemNum].setStyleSheet("background-color: #ffffe0;")
        elif i.upper() == "STOP":
            ui.cist[itemNum].setStyleSheet("background-color: #ffcccb;")
        elif i.upper() == "WORKED":
            ui.cist[itemNum].setStyleSheet("background-color: #CBC3E3;")


        '''Error position'''
        print(IList[itemNum], ui.cist[itemNum].objectName(), itemNum)

        itemNum += 1
        # if itemNum == 37:
        #     itemNum = 36
    Main.show()
    sys.exit(app.exec_())


import sys
print(sys.argv)
if len(sys.argv) > 1:
    car_num = sys.argv[1]
    StatusList = sys.argv[2].split(",")
    main(car_num, StatusList)

else:
    # main("7022")
    InspOverview.main("7029", "COT")


# if __name__ == "__main__":
        # import sys
        #
        # '''grab the function by values'''

        # app = QtWidgets.QApplication(sys.argv)
        # Main = QtWidgets.QMainWindow()
        # ui = Ui_Main(car_num=7777)
        # ui.setupUi(Main)
        # ui.cist[1].setStyleSheet("background-color: #ffcccb;")
        # Main.show()
        # sys.exit(app.exec_())

